# Generated by Django 4.0 on 2021-12-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'CONFIG CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='ConfigChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='choice/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.configcategory', verbose_name='choice')),
            ],
            options={
                'verbose_name_plural': 'CONFIG CHOICE',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='ad/')),
                ('ad_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.configchoice')),
            ],
            options={
                'verbose_name_plural': 'AD',
            },
        ),
    ]
