services:
  web:
    build: .
    container_name: portfolio
    command: "gunicorn Portfolio.wsgi:application --bind 0.0.0.0:8005"

    volumes:
      - .:/app
    ports:
      - "8005:8005"
    env_file:
      - .env
    restart: unless-stopped









