# Generated by Django 3.2.9 on 2022-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_about_education_experience_fact_portfolio_skills_task_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='', upload_to='profile'),
            preserve_default=False,
        ),
    ]
