# Generated by Django 3.2.9 on 2022-02-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220206_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='bod',
            new_name='dob',
        ),
    ]
