# Generated by Django 3.2.9 on 2022-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_bod_about_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='ghimire', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='freelance',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200),
        ),
    ]
