# Generated by Django 3.2.9 on 2022-02-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institute_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
            preserve_default=False,
        ),
    ]
