# Generated by Django 3.2.9 on 2022-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_education_institute_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='current_now',
            field=models.BooleanField(),
        ),
    ]
