# Generated by Django 3.2.9 on 2022-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_education_current_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
