# Generated by Django 3.2.9 on 2022-02-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_experience_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='current_working',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
