# Generated by Django 3.2.9 on 2022-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='job_title',
            field=models.CharField(default='Python Developer', max_length=200),
            preserve_default=False,
        ),
    ]
