# Generated by Django 3.2.9 on 2022-02-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_about_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(default='1234-2-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='logo',
            field=models.ImageField(default='asdfs', upload_to='portfolio/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(default='1234-4-4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(default='asdf'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.portfolio')),
            ],
        ),
    ]
