# Generated by Django 3.2.9 on 2022-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_myuser_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='experience',
        ),
        migrations.AddField(
            model_name='about',
            name='awards',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='client',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='project',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='support',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
