# Generated by Django 4.0 on 2021-12-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('accounts', '0004_contact_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_now', models.CharField(max_length=10)),
                ('institute', models.CharField(max_length=250)),
                ('marks', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'EDUCATION',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'EXPERIENCE',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=250)),
                ('profile', models.ImageField(upload_to='testimonials/')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TESTIMONIALS',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_details.experience')),
            ],
            options={
                'verbose_name_plural': 'TASK',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.configchoice')),
            ],
            options={
                'verbose_name_plural': 'SKILLS',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.configchoice')),
            ],
            options={
                'verbose_name_plural': 'PORTFOLIO',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='fact-logo')),
                ('description', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.configchoice')),
            ],
            options={
                'verbose_name_plural': 'FACT',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('bod', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('freelance', models.CharField(choices=[('Avaiable', 'Avaiable'), ('Not Avaiable', 'Not Avaiable')], max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.myuser')),
            ],
            options={
                'verbose_name_plural': 'ABOUT',
            },
        ),
    ]
